### ISSUE TITLE
Roadmap for ShadowNode v1.0.0

### ISSUE THREAD

**Issue by legendecas** [yodaos-project/ShadowNode#496]
### Performance
* [ ]  Computed goto statement for vm interpreter
* [ ]  Forced byte code pre-compilation on host/no parse-phase on target devices

### Development Experience:
* [ ]  Better Debugger Support
  - [ ] Variable inspection/watch
  - [ ] Break on start
* [ ] Better Profiler Interface

### API
* [ ] Async Hooks Support
